#!/bin/bash
# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear
set -euo pipefail

nvidia_entrypoint=/opt/nvidia/nvidia_entrypoint.sh

if [[ "$(id -u)" != "0" ]]; then
    exec "${nvidia_entrypoint}" "$@"
fi

find_host_dotfiles_dir() {
    if [[ -n "${HOST_DOTFILES_DIR:-}" ]]; then
        printf '%s\n' "${HOST_DOTFILES_DIR}"
        return
    fi

    if [[ -d /host_home ]]; then
        if [[ -f /host_home/.bashrc || -f /host_home/.bachrc || -f /host_home/.profile.local ]]; then
            printf '%s\n' /host_home
            return
        fi

        local candidate
        for candidate in /host_home/*; do
            if [[ -d "${candidate}" ]]; then
                printf '%s\n' "${candidate}"
                return
            fi
        done
    fi

    printf '%s\n' /host_home
}

stat_uid_gid() {
    local path="$1"
    [[ -e "${path}" ]] || return 1
    stat -c '%u:%g' "${path}" 2>/dev/null || return 1
}

host_dotfiles_dir="$(find_host_dotfiles_dir)"
host_home="${HOST_HOME:-/tmp}"
host_uid="${HOST_UID:-}"
host_gid="${HOST_GID:-}"

if [[ -z "${host_uid}" || -z "${host_gid}" ]]; then
    identity_paths=()
    [[ -n "${HOST_ID_PATH:-}" ]] && identity_paths+=("${HOST_ID_PATH}")
    identity_paths+=("${host_dotfiles_dir}" /workspace/hf_cache "$(pwd)")

    for identity_path in "${identity_paths[@]}"; do
        uid_gid="$(stat_uid_gid "${identity_path}" || true)"
        [[ -n "${uid_gid}" ]] || continue
        detected_uid="${uid_gid%%:*}"
        detected_gid="${uid_gid##*:}"
        if [[ "${detected_uid}" != "0" ]]; then
            host_uid="${host_uid:-${detected_uid}}"
            host_gid="${host_gid:-${detected_gid}}"
            break
        fi
    done
fi

if [[ -z "${host_uid}" || "${host_uid}" == "0" ]]; then
    exec "${nvidia_entrypoint}" "$@"
fi

host_gid="${host_gid:-${host_uid}}"
host_user="${HOST_USER:-}"
if [[ -z "${host_user}" && "${host_dotfiles_dir}" == /host_home/* ]]; then
    host_user="$(basename "${host_dotfiles_dir}")"
fi
host_user="${host_user:-hostuser_${host_uid}}"
host_group="${HOST_GROUP:-hostgroup_${host_gid}}"

host_user="${host_user//[^[:alnum:]_.-]/_}"
host_group="${host_group//[^[:alnum:]_.-]/_}"

if ! getent group "${host_gid}" >/dev/null; then
    if ! groupadd --gid "${host_gid}" "${host_group}" 2>/dev/null; then
        groupadd --gid "${host_gid}" "hostgroup_${host_gid}"
    fi
fi

if [[ -n "${HOST_GROUPS:-}" ]]; then
    for supplemental_gid in ${HOST_GROUPS}; do
        if ! getent group "${supplemental_gid}" >/dev/null; then
            groupadd --gid "${supplemental_gid}" "hostgroup_${supplemental_gid}"
        fi
    done
fi

mkdir -p "${host_home}" 2>/dev/null || true
touch "${host_home}/.hushlogin" 2>/dev/null || true

if [[ -d "${host_dotfiles_dir}" ]]; then
    dotfiles_to_source=()
    for dotfile in .bashrc .bachrc .profile.local; do
        if [[ -f "${host_dotfiles_dir}/${dotfile}" ]]; then
            dotfiles_to_source+=("${host_dotfiles_dir}/${dotfile}")
        fi
    done

    if [[ "${#dotfiles_to_source[@]}" -gt 0 ]]; then
        {
            echo "# Generated by scratchpad-entrypoint.sh."
            for dotfile_path in "${dotfiles_to_source[@]}"; do
                printf '[[ -r %q ]] && source %q\n' "${dotfile_path}" "${dotfile_path}"
            done
        } >"${host_home}/.bashrc" 2>/dev/null || true

        cat >"${host_home}/.bash_profile" 2>/dev/null <<'PROFILE_EOF' || true
[[ -r ~/.bashrc ]] && source ~/.bashrc
PROFILE_EOF
    fi
fi

if ! getent passwd "${host_uid}" >/dev/null; then
    if ! useradd \
        --uid "${host_uid}" \
        --gid "${host_gid}" \
        --home-dir "${host_home}" \
        --shell /bin/bash \
        --no-create-home \
        "${host_user}" 2>/dev/null; then
        useradd \
            --uid "${host_uid}" \
            --gid "${host_gid}" \
            --home-dir "${host_home}" \
            --shell /bin/bash \
            --no-create-home \
            "hostuser_${host_uid}"
    fi
fi

resolved_user="$(getent passwd "${host_uid}" | cut -d: -f1)"
export HOME="${host_home}"
export USER="${resolved_user}"
export LOGNAME="${resolved_user}"

setpriv_args=(--reuid "${host_uid}" --regid "${host_gid}")
if [[ -n "${HOST_GROUPS:-}" ]]; then
    setpriv_args+=(--groups "${HOST_GROUPS// /,}")
else
    setpriv_args+=(--clear-groups)
fi

exec setpriv "${setpriv_args[@]}" "${nvidia_entrypoint}" "$@"
